- smoderp2d/io_functions/hydrographs.py
- smoderp2d/providers/arcgis/data_preparation.py
- smoderp2d/providers/arcgis/stream_preparation.py
- smoderp2d/providers/base/__init__.py
- smoderp2d/providers/base/data_preparation.py
preprocessing: intersection of points and streams were moved from temp into core/data.gdb directory (on @kavkapet request)
io: hydrographs (point?.dat) are now stored in output/core directory. 
prepossessing: stream.csv are now stored in output/core directory. 
Tested with arcmap 10.7 only.
Close issue #62 after the merge is done.
@landam have a look at the changes
> Issue 62 output temp

- smoderp2d/core/vegetation.py
- smoderp2d/processes/rainfall.py
- smoderp2d/providers/cmd/__init__.py
- smoderp2d/runoff.py
- smoderp2d/time_step.py
tested only at nucice data (provided testing dataset)
> Issue 78 interception error

- bin/base/__init__.py
- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
> create dynamic gui

- smoderp2d/processes/rainfall.py
while loop style was corresponding to smoderp 1.0.0
> fix ArcGIS timestepRainfall loop

- smoderp2d/processes/infiltration/__init__.py
> set error level of numpy float underflow only to warning

- smoderp2d/providers/grass/data_preparation.py
> fix environment can only contain strings

- smoderp2d/flow_algorithm/py_dmtfce.py
avoid making mistakes in individial cases of a repeated ctrl-c ctrl-v code
> py_dmtfce: create a function for getting direction and slope

- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
- smoderp2d/providers/arcgis/data_preparation.py
- smoderp2d/providers/base/data_preparation.py
- smoderp2d/providers/grass/data_preparation.py
> Check streams_channel_type_fieldname

- smoderp2d/flow_algorithm/py_dmtfce.py
no need to run the loop through all cells twice
> optimise same height cells settings

- smoderp2d/providers/base/data_preparation.py
> do not ignore points in border cells

- smoderp2d/flow_algorithm/D8.py
noticeably speeds up the algorithm
> new_inflows: avoid running the same loop three times

- .github/workflows/grass_provider.yml
- tests/run_grass_gistest.sh
- tests/test_arcgis.py
- tests/test_grass.py
- new shell script to run tests
- rename 003 to 002
> Run gistests by shell script

- README.md
- bin/arcgis/SMODERP2D.pyt
- bin/grass/r.smoderp2d/r.smoderp2d.py
- smoderp2d/.config.ini
- smoderp2d/providers/base/__init__.py
- GRASS GIS UI modified
- ArcGIS UI modified
> Move dpre_only option to hidden config

- smoderp2d/providers/base/__init__.py
> Catch permission error

- smoderp2d/time_step.py
> time_step: move global variables to be class variables

- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
> QGIS: fix points field cannot be unset once points were set

- .github/workflows/cmd_template.yml
- bin/arcgis/SMODERP2D.pyt
- smoderp2d/providers/base/__init__.py
- smoderp2d/providers/profile1d/__init__.py
- tests/test_utils.py
- utils/convert-saved-data.py
> drop support for Python 2

- smoderp2d/processes/rainfall.py
also, refactor the corresponding code a bit
> fix comma in rainfall file causing crash

- smoderp2d/providers/grass/data_preparation.py
only multiple outflows from one stream is considered bifurcation, multiple inflows are fine
see #339
> fix fake bifurcation detection

- smoderp2d/providers/grass/data_preparation.py
> fix streams snapped to lines instead of points

- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
> fix failing QGIS with tables imported via Data Source Manager

- smoderp2d/exceptions.py
- smoderp2d/processes/rainfall.py
- smoderp2d/providers/base/__init__.py
- smoderp2d/providers/base/data_preparation.py
- smoderp2d/providers/profile1d/__init__.py
- define RainDataError in smoderp2d.exceptions
- check rainfall data existence on startup
> better handling of rainfall data errors

- smoderp2d/flow_algorithm/py_dmtfce.py
> mfda: fix wrong nodata value used

- smoderp2d/core/surface.py
- smoderp2d/courant.py
- smoderp2d/io_functions/hydrographs.py
- smoderp2d/processes/rainfall.py
- smoderp2d/runoff.py
> delta_t, total_time: use scalars instead of matrices

- smoderp2d/core/stream.py
- smoderp2d/stream_functions/stream_f.py
> streams: change matrices to scalars where possible

- smoderp2d/providers/cmd/__init__.py
- tests/test_utils.py
> cmd provider: add geoinformation header into *.asc files

- smoderp2d/providers/base/data_preparation.py
no need to run nsheet and y value checks twice
> data_preparation._get_a: optimize algorithm

- smoderp2d/core/cumulative_max.py
more readable and slightly faster
> cumulative_max: simplify conditions to maximum() operations

- smoderp2d/flow_algorithm/py_dmtfce.py
replace by numpy operation
noticeable speedup for MFDA
> removeCellsWithSameHeightNeighborhood: avoid third-generation loop

- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
> QGIS plugin: be less verbose about historical items for which the loading failed

- README.md
- bin/qgis/grass_patch/core.py
- bin/qgis/smoderp2d-plugin/smoderp_2D_dockwidget.py
- smoderp2d/runners/grass.py
QGIS now reports this issue to users:
> Check for patch in GRASS 8.3

- smoderp2d/runoff.py
makes the initialisation code a bit cleaner
> runoff: create record_hydrographs_time_zero() method

- bin/grass/r.smoderp2d/r.smoderp2d.html
- bin/grass/r.smoderp2d/r.smoderp2d.py
> Enable installing grass addon by using gextension
